### ISSUE TITLE
Does not compile in VS2012 OF0.8.1

### ISSUE THREAD

**Issue by SR--** [morethanlogic/ofxMtlMapping2D#5]
Here are the errors:

...\of_v0.8.1_vs_release\addons\ofxmtlmapping2d\src\shapes\ofxmtlmapping2dpolygon.cpp(166): error C2001: newline in constant
...\of_v0.8.1_vs_release\addons\ofxmtlmapping2d\src\shapes\ofxmtlmapping2dpolygon.cpp(166): error C2015: too many characters in constant

These are the lines:

``` C++
#pragma mark -
#pragma mark Update Shape's elemets
```

**Comment by smallfly** [comment]
Hi,

Sorry for the late reply. You must have solved that by now. 
This is the ' character that is causing this issue on Windows / VS. You can check the branch Develop.
